### ISSUE TITLE
How do you get source/nq-qa

### ISSUE THREAD

**Issue by ShiyuNee** [yhao-wang/LLM-Knowledge-Boundary#2]
How do you get source/nq-qa from the original NQ dataset?

**Comment by yhao-wang** [comment]
We use the same splitting method as [DPR](https://github.com/facebookresearch/dpr) and [RocketQAv2](https://github.com/PaddlePaddle/RocketQA/). You can run ```bash preparation.sh``` to get the original data.

**Comment by ShiyuNee** [comment]
> We use the same splitting method as [DPR](https://github.com/facebookresearch/dpr) and [RocketQAv2](https://github.com/PaddlePaddle/RocketQA/). You can run `bash preparation.sh` to get the original data.

Thanks!
